address = "127.0.0.1:10000"
domain = "ruda.app"
version = "0.1.0"

local_runner = true

[dev] 
enabled = false
mock = true
mock_regen = true
# autologin = "test@mail.com"

[assets]
serve = false

[registration]
enabled = true
email = true
oauth = true

[oauth]
enabled = true
